spring:
  datasource:
    url: jdbc:postgresql://powercoffee-database-server.postgres.database.azure.com:5432/powercoffee
    username: sqladmin
    password: Computador1308*

  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: servicioalcliente.powercoffee@gmail.com
    password: nhdpchodeevrnxxt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

server:
  port: 80

powercoffee:
  app:
    jwtSecret: hcyj3cDPGJNPmZMMipmQSbeH37gTknV6tFjoDaQwWw8rstJahUEiSFfgMqqpc2znKrpLC9mtfRe2aqLExCuBGXyWNhr9PyNQ8iykoMTuSqDRgw6w9bdYtyUkP2i9eSZX
    jwtExpirationMs: 86400000